disabled_rules:
- trailing_whitespace
- switch_case_alignment
- switch_case_on_newline 

line_length:
- 300 # warning
- 400 # error

variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

force_cast: warning
